In [7]:
!pip install tensorflow

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
voc_size=10000

In [6]:
one_hot_repr=[one_hot(words,voc_size )for words in sent]
one_hot_repr

[[7914, 6839, 9895, 454],
 [7914, 6839, 9895, 7715],
 [7914, 7088, 9895, 6532],
 [5755, 1769, 9076, 3762, 7800],
 [5755, 1769, 9076, 3762, 4152],
 [5497, 7914, 6318, 9895, 3892],
 [7481, 1819, 5754, 3762]]

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7914 6839 9895  454]
 [   0    0    0    0 7914 6839 9895 7715]
 [   0    0    0    0 7914 7088 9895 6532]
 [   0    0    0 5755 1769 9076 3762 7800]
 [   0    0    0 5755 1769 9076 3762 4152]
 [   0    0    0 5497 7914 6318 9895 3892]
 [   0    0    0    0 7481 1819 5754 3762]]


In [12]:
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
 model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 301ms/step


array([[[ 0.02846849, -0.00594058,  0.03859266, -0.00804146,
          0.02948171, -0.03154244, -0.00110042,  0.00418054,
          0.0311669 ,  0.00444734],
        [ 0.02846849, -0.00594058,  0.03859266, -0.00804146,
          0.02948171, -0.03154244, -0.00110042,  0.00418054,
          0.0311669 ,  0.00444734],
        [ 0.02846849, -0.00594058,  0.03859266, -0.00804146,
          0.02948171, -0.03154244, -0.00110042,  0.00418054,
          0.0311669 ,  0.00444734],
        [ 0.02846849, -0.00594058,  0.03859266, -0.00804146,
          0.02948171, -0.03154244, -0.00110042,  0.00418054,
          0.0311669 ,  0.00444734],
        [ 0.00597098,  0.01902895, -0.04288064, -0.00281707,
          0.00933348,  0.04044345, -0.01354546,  0.0154216 ,
         -0.02148387,  0.01529162],
        [ 0.00843971,  0.01988107,  0.03030679,  0.02859661,
         -0.04293525, -0.02193522, -0.01216946,  0.02353356,
         -0.03864528,  0.03515209],
        [ 0.02499653,  0.04399021, -0.00938723, -0.0